
# exp_internal 1

### test for simple schema dropping
set test_name "test for simple schema dropping"
# simple drop table statements should drop the table of the given name
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same should happen if the other table is dropped
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.testtable2;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same should happen if the schema name is quoted using backticks
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table `test`.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same should happen if the table name is quoted using backticks
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.`testtable1`;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same thing should happen if the `if exists` qualifier is used
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table if exists test.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same thing should happen if a use schema statement is in effect
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "use test;\r" \
  then I should see "ok" \
  when I send "drop table testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should be case insensitive
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "DROP TABLE test.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0

### test for table dropping using weird names
set test_name "test for table droppig using weird names"
# the query should succeed if the valid charset is used (schema)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema abcxyzABCXYZ012_$;\r" \
  then I should see "ok" \
  when I send "create table abcxyzABCXYZ012_$.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table abcxyzABCXYZ012_$.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table abcxyzABCXYZ012_$.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should fail if invalid characters are used (schema)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema `test:schema`;\r" \
  then I should see "ok" \
  when I send "create table `test:schema`.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table `test:schema`.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test:schema.testtable1;\r" \
  then I should see "error: syntax error" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "testtable2" \
  and I should see "ok: returned 2 rows" \
  and it should return 0
# the query should succeed if the identifier is quoted (schema)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema `test:schema`;\r" \
  then I should see "ok" \
  when I send "create table `test:schema`.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table `test:schema`.testtable2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table `test:schema`.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should succeed if the valid charset is used (table)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.abcxyzABCXYZ012_\$1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.abcxyzABCXYZ012_\$2 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.abcxyzABCXYZ012_\$1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "abcxyzABCXYZ012_\\\$2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should fail if invalid characters are used (table)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.`test:table1` ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.`test:table2` ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.test:table1;\r" \
  then I should see "error: syntax error" \
  when I send "show tables;\r\x04" \
  then I should see "test:table1" \
  and I should see "test:table2" \
  and I should see "ok: returned 2 rows" \
  and it should return 0
# the query should succeed if the identifier is quoted (table)
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.`test:table1` ( col int );\r" \
  then I should see "ok" \
  when I send "create table test.`test:table2` ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.`test:table1`;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "test:table2" \
  and I should see "ok: returned 1 rows" \
  and it should return 0

### test for table dropping on nonexistant tables
set test_name "test for table dropping on nonexistant tables"
# the query should fail if a table of the given name does not exist
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.testtable2;\r" \
  then I should see "error: table `testtable2`: does not exist" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same should happen if the table name is quoted
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.`testtable2`;\r" \
  then I should see "error: table `testtable2`: does not exist" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should fail if a schema of the given name does not exist
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test1;\r" \
  then I should see "ok" \
  when I send "create table test1.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test2.testtable1;\r" \
  then I should see "error: schema `test2`: does not exist" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the same should happen if the schema name is quoted
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test1;\r" \
  then I should see "ok" \
  when I send "create table test1.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table `test2`.testtable1;\r" \
  then I should see "error: schema `test2`: does not exist" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should fail if the name differs only in case
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table test.TESTTABLE1;\r" \
  then I should see "error: table `TESTTABLE1`: does not exist" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0
# the query should succeed if the `if exists` qualifier is used
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create table test.testtable1 ( col int );\r" \
  then I should see "ok" \
  when I send "drop table if exists test.testtable2;\r" \
  then I should see "ok" \
  when I send "drop table if exists test1.testtable1;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "testtable1" \
  and I should see "ok: returned 1 rows" \
  and it should return 0

### test for the dropping of multiple tables
set test_name "test for the dropping of multiple tables"
# try to create 10 tables in 2 schemata and drop them
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema schema1;\r" \
  then I should see "ok" \
  when I send "create schema schema2;\r" \
  then I should see "ok" \
  when I send "create table schema1.table1 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema1.table2 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema1.table3 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table4 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table5 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table6 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table7 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table8 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table9 ( col int );\r" \
  then I should see "ok" \
  when I send "create table schema2.table10 ( col int );\r" \
  then I should see "ok" \
  when I send "show tables;\r" \
  then I should see "table1" \
  and I should see "table2" \
  and I should see "table3" \
  and I should see "table4" \
  and I should see "table5" \
  and I should see "table6" \
  and I should see "table7" \
  and I should see "table8" \
  and I should see "table9" \
  and I should see "table10" \
  and I should see "ok: returned 10 rows" \
  when I send "drop table schema1.table1;\r" \
  then I should see "ok" \
  when I send "drop table schema1.table2;\r" \
  then I should see "ok" \
  when I send "drop table schema1.table3;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table4;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table5;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table6;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table7;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table8;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table9;\r" \
  then I should see "ok" \
  when I send "drop table schema2.table10;\r" \
  then I should see "ok" \
  when I send "show tables;\r\x04" \
  then I should see "ok: returned 0 rows" \
  and it should return 0

send_user "\n"
