
# exp_internal 1

set test_name "create a non-existing schema"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema `test`;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "test" \
  and it should return 0 \
  when I run \
  and I send "create database `test`;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "test" \
  and it should return 0 \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "test" \
  and it should return 0 \
  when I run \
  and I send "create database test;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "test" \
  and it should return 0


set test_name "create an existing schema"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema `test`;\r" \
  then I should see "ok" \
  when I send "create schema `test`;\r" \
  then I should see "error: schema `test`: already exists" \
  when I send "create schema if not exists `test`;\r\x04" \
  then I should see "ok" \
  and it should return 0 \
  when I run \
  and I send "create database `test`;\r" \
  then I should see "ok" \
  when I send "create database `test`;\r" \
  then I should see "error: schema `test`: already exists" \
  when I send "create database if not exists `test`;\r\x04" \
  then I should see "ok" \
  and it should return 0 \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "create schema test;\r" \
  then I should see "error: schema `test`: already exists" \
  when I send "create schema if not exists test;\r\x04" \
  then I should see "ok" \
  and it should return 0 \
  when I run \
  and I send "create database test;\r" \
  then I should see "ok" \
  when I send "create database test;\r" \
  then I should see "error: schema `test`: already exists" \
  when I send "create database if not exists test;\r\x04" \
  then I should see "ok" \
  and it should return 0


set test_name "create multiple schemata"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create database test1;\r" \
  then I should see "ok" \
  when I send "create database test2;\r" \
  then I should see "ok" \
  when I send "create database test3;\r" \
  then I should see "ok" \
  when I send "create database test4;\r" \
  then I should see "ok" \
  when I send "create database test5;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "database" \
  and I should see "returned 5 rows" \
  and it should return 0


send_user "\n"
