
# exp_internal 1

set test_name "drop an existing schema"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema `test`;\r" \
  then I should see "ok" \
  when I send "drop schema `test`;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "create database `test`;\r" \
  then I should see "ok" \
  when I send "drop database `test`;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "create schema test;\r" \
  then I should see "ok" \
  when I send "drop schema test;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "create database test;\r" \
  then I should see "ok" \
  when I send "drop database test;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0


set test_name "drop a non-existing schema"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "drop schema `test`;\r" \
  then I should see "error: schema `test`: does not exist" \
  when I send "drop schema if exists `test`;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "drop database `test`;\r" \
  then I should see "error: schema `test`: does not exist" \
  when I send "drop database if exists `test`;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "drop schema test;\r" \
  then I should see "error: schema `test`: does not exist" \
  when I send "drop schema if exists test;\r" \
  then I should see "ok" \
  when I send "show schemata;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0 \
  when I run \
  and I send "drop database test;\r" \
  then I should see "error: schema `test`: does not exist" \
  when I send "drop database if exists test;\r" \
  then I should see "ok" \
  when I send "show databases;\r\x04" \
  then I should see "returned 0 rows" \
  and it should return 0


set test_name "drop multiple schemata"
given an executable "../pinedb/pinedb" \
  when I run \
  and I send "create schema test1;\r" \
  then I should see "ok" \
  when I send "create schema test2;\r" \
  then I should see "ok" \
  when I send "create schema test3;\r" \
  then I should see "ok" \
  when I send "create schema test4;\r" \
  then I should see "ok" \
  when I send "create schema test5;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 5 rows" \
  when I send "drop schema test2;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 4 rows" \
  when I send "drop schema test4;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 3 rows" \
  when I send "drop schema test1;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 2 rows" \
  when I send "drop schema test5;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 1 rows" \
  when I send "drop schema test3;\r" \
  then I should see "ok" \
  when I send "show schemata;\r" \
  then I should see "returned 0 rows" \


send_user "\n"
