
### test for output formatting of show schemata query
set test_name "test for output formatting of show schemata query"
# the show schemata query should return one line per schema
given an executable "../pinedb/pinedb"
  when I run
  and I send "create schema test1;\r"
  then I should see "ok"
  when I send "create schema test2;\r"
  then I should see "ok"
  when I send "show schemata;\r\x04"
  then I should see "test1"
  and I should see "test2"
  and I should see "ok: returned 2 rows"
  and it should return 0
# the same thing should happen if `databases` is used instead of `schemata`
given an executable "../pinedb/pinedb"
  when I run
  and I send "create schema test1;\r"
  then I should see "ok"
  when I send "create schema test2;\r"
  then I should see "ok"
  when I send "show databases;\r\x04"
  then I should see "test1"
  and I should see "test2"
  and I should see "ok: returned 2 rows"
  and it should return 0
# if no schemata are present, the query should succeed with an empty result set
given an executable "../pinedb/pinedb"
  when I run
  and I send "show schemata;\r\x04"
  then I should see "ok: returned 0 rows"
  and it should return 0
# the query should be case insensitive
given an executable "../pinedb/pinedb"
  when I run
  and I send "SHOW SCHEMATA;\r\x04"
  then I should see "ok: returned 0 rows"
  and it should return 0
# the output should be a nice table
given an executable "../pinedb/pinedb"
  when I run
  and I send "show schemata;\r"
  then I should see "+----------+"
  and I should see  "| database |"
  and I should see  "|----------|"
  and I should see  "+----------+"
  and I should see  "ok: returned 0 rows"
  when I send "create schema short;\r"
  then I should see "ok"
  when I send "show schemata;\r"
  then I should see "+----------+"
  and I should see  "| database |"
  and I should see  "|----------|"
  and I should see  "|    short |"
  and I should see  "+----------+"
  and I should see  "ok: returned 1 rows"
  when I send "create schema veryveryveryveryveryverylong;\r"
  then I should see "ok"
  when I send "show schemata;\r\x04"
  then I should see "+------------------------------+"
  and I should see  "|                     database |"
  and I should see  "|------------------------------|"
  and I should see  "|                        short |"
  and I should see  "| veryveryveryveryveryverylong |"
  and I should see  "+------------------------------+"
  and I should see  "ok: returned 2 rows"
  and it should return 0

send_user "\n"
